apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: akul-v39
spec:
  replicas: 3
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
        - name: api-gateway
          image: akuldravin/api-gateway:v39.0.0
          ports:
            - containerPort: 4200
          envFrom:
            - configMapRef:
                name: platform-config
          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "1"
              memory: "1Gi"
---
apiVersion: v1
kind: Service
metadata:
  name: api-gateway
  namespace: akul-v39
spec:
  selector:
    app: api-gateway
  ports:
    - name: http
      port: 80
      targetPort: 4200
  type: ClusterIP
