import { DomainEventName } from '../governance/events/domain-events';

/**
 * DOMAIN EVENT ENVELOPE
 *
 * The typed container for every domain event flowing through the bus.
 * All handlers receive this shape — they extract what they need.
 *
 * ── Traceability fields ──────────────────────────────────────────────────────
 *  correlationId  threads the event back to the originating HTTP request trace.
 *  causationId    identifies the upstream event that caused THIS event —
 *                 enabling full event lineage reconstruction (event DAG).
 *  tenantId       mandatory — the bus is always tenant-scoped.
 *  occurredAt     immutable — set at emission time, not handler time.
 *
 * ── Idempotency fields ───────────────────────────────────────────────────────
 *  id             a unique UUID generated at emission time by the bus.
 *                 Handlers use this for deduplication — if the same event
 *                 arrives twice (retry, redelivery, replay), handlers check
 *                 this ID before writing to prevent duplicate projection writes.
 *
 * ── Aggregate fields (replay partitioning) ───────────────────────────────────
 *  aggregateId    the root entity ID (taskId, employeeId, payrollBatchId, etc.)
 *                 Used for replay filtering: "replay all events for taskId=X".
 *  aggregateType  the entity class name ('Task', 'PayrollBatch', 'Employee').
 *                 Used for replay filtering by type: "replay all Task events".
 *
 * ── Version field ────────────────────────────────────────────────────────────
 *  version        monotonically increasing sequence number for the aggregate.
 *                 Enables optimistic concurrency detection during replay:
 *                 if two handlers see version=3 for the same aggregateId,
 *                 the second is a duplicate and should be discarded.
 *                 Optional — set by callers with event-sourced aggregates.
 */
export interface DomainEventEnvelope<T = Record<string, unknown>> {
  /**
   * Unique ID for this event instance — generated by the bus at emission time.
   * UUID v4. Used by handlers for idempotent projection writes.
   * If an event is retried or replayed, this ID is preserved so handlers
   * can detect and skip duplicate processing.
   */
  readonly id: string;

  /** Canonical event name from domain-events.ts. */
  readonly event: DomainEventName;

  /** Tenant that originated this event — never nullable. */
  readonly tenantId: string;

  /** Request correlation ID for distributed tracing — threads back to HTTP request. */
  readonly correlationId: string | undefined;

  /**
   * ID of the upstream event that caused this event.
   * When TaskCreated causes AuditEntryWritten, the audit event's causationId
   * is the TaskCreated event's id. Enables full event lineage graph reconstruction.
   */
  readonly causationId: string | undefined;

  /** ISO timestamp of event emission — set by bus, immutable in handlers. */
  readonly occurredAt: string;

  /** Actor (user/system) that triggered the originating operation. */
  readonly actorId: string | undefined;

  /**
   * ID of the root aggregate (task.id, payrollBatch.id, employee.id, etc.).
   * Used for replay partitioning: "replay all events for aggregate X".
   */
  readonly aggregateId: string | undefined;

  /**
   * Class name of the root aggregate ('Task', 'PayrollBatch', 'Employee').
   * Used for replay filtering: "replay all Task events for this tenant".
   */
  readonly aggregateType: string | undefined;

  /**
   * Monotonic sequence number for this aggregate's event stream.
   * Used for optimistic concurrency detection during replay.
   * Optional — only set by callers managing event-sourced aggregates.
   */
  readonly version: number | undefined;

  /** Event-specific payload. */
  readonly payload: T;
}

/**
 * PROJECTION HANDLER
 *
 * A projection handler consumes a domain event and produces a side effect
 * in a downstream system (audit, search, activity, notifications).
 *
 * Handlers declare:
 *  - handles: which event names they consume
 *  - severity: what failure means (mirrors ContractEffect.severity)
 *  - handle(): the async side effect
 *
 * Severity semantics:
 *  critical    → handler failure throws, aborting the calling operation.
 *  eventual    → handler failure is logged, operation continues.
 *  best_effort → handler failure is swallowed silently.
 */
export interface ProjectionHandler<T = Record<string, unknown>> {
  /** Event names this handler consumes. */
  readonly handles: ReadonlyArray<DomainEventName>;

  /**
   * Failure behaviour when this handler throws.
   * Must match the ContractEffect.severity for the events it handles.
   */
  readonly severity: 'critical' | 'eventual' | 'best_effort';

  /**
   * Human-readable name for logging and trace attribution.
   * Used in DomainEventBus error messages and observability tags.
   */
  readonly name: string;

  /** Execute the projection. Throws on failure. */
  handle(envelope: DomainEventEnvelope<T>): Promise<void>;
}
