'use client'; import { ReactNode } from 'react';
import { Lock, Sparkles, ArrowRight } from 'lucide-react';
import Link from 'next/link'; /* ── Types ───────────────────────────────────────────────────────────────────── */ export type PlanTier = | 'free' | 'hr-lite' | 'hr-pro' | 'hr-payroll' | 'business' | 'premium' | 'enterprise' | 'starter' | 'growth' | 'pro'; interface FeatureGateProps { /** The content to render when the feature is available */ children: ReactNode; /** Whether the current user's plan includes this feature */ enabled: boolean; /** Human-readable name of the feature */ featureName: string; /** The minimum plan tier required */ requiredPlan?: PlanTier; /** Whether to show a compact inline badge instead of the full overlay */ compact?: boolean; /** Custom upgrade CTA link */ upgradeHref?: string;
} const PLAN_LABELS: Record<PlanTier, string> = { free: 'Free Plan', 'hr-lite': 'HR Lite (₹999)', 'hr-pro': 'HR Pro (₹2,499)', 'hr-payroll': 'HR + Payroll (₹4,999)', business: 'Business HRMS (₹9,999)', premium: 'Premium HRMS (₹17,999)', enterprise: 'Enterprise', starter: 'HR Starter', growth: 'HR Growth', pro: 'HR Pro',
}; const PLAN_COLORS: Record<PlanTier, string> = { free: 'from-slate-500 to-slate-600', 'hr-lite': 'from-blue-500 to-indigo-600', 'hr-pro': 'from-cyan-500 to-teal-600', 'hr-payroll': 'from-emerald-500 to-green-600', business: 'from-amber-500 to-orange-600', premium: 'from-purple-500 to-violet-600', enterprise: 'from-rose-500 to-pink-700', starter: 'from-slate-500 to-slate-600', growth: 'from-aqua to-teal-600', pro: 'from-gold to-amber-600',
}; /* ── Compact Badge ───────────────────────────────────────────────────────────── */ function CompactGate({ featureName, requiredPlan }: { featureName: string; requiredPlan?: PlanTier }) { return ( <span className="inline-flex items-center gap-1 rounded-full bg-gold/15 border border-gold/25 px-2.5 py-1 text-[10px] font-bold text-gold"title={`${featureName} requires ${requiredPlan ? PLAN_LABELS[requiredPlan] : 'a higher plan'}`} > <Lock className="h-3 w-3"/> {requiredPlan ? PLAN_LABELS[requiredPlan] : 'Upgrade'} </span> );
} /* ── Full Gate Overlay ───────────────────────────────────────────────────────── */ function FullGate({ featureName, requiredPlan, upgradeHref = '/plan-catalog',
}: { featureName: string; requiredPlan?: PlanTier; upgradeHref?: string;
}) { const gradientClass = requiredPlan ? PLAN_COLORS[requiredPlan] : 'from-gold to-amber-600'; const planLabel = requiredPlan ? PLAN_LABELS[requiredPlan] : 'a higher plan'; return ( <div className="relative flex flex-col items-center justify-center rounded-2xl border border-white/8 bg-white/[0.02] px-8 py-12 text-center"role="status"aria-label={`${featureName} requires ${planLabel}`} > {/* Lock icon */} <div className={`mb-4 flex h-16 w-16 items-center justify-center rounded-2xl bg-gradient-to-br ${gradientClass} shadow-lg`}> <Lock className="h-8 w-8 text-white"/> </div> {/* Plan badge */} {requiredPlan && ( <span className={`mb-3 inline-flex items-center gap-1.5 rounded-full bg-gradient-to-r ${gradientClass} px-3 py-1 text-xs font-bold text-navy shadow`}> <Sparkles className="h-3 w-3"/> {PLAN_LABELS[requiredPlan]} </span> )} <h3 className="text-base font-bold text-navy">{featureName}</h3> <p className="mt-2 max-w-xs text-sm text-slate-500"> This feature is available on {planLabel} and above. Upgrade your plan to unlock it. </p> {/* CTA */} <Link href={upgradeHref} className="mt-6 inline-flex items-center gap-2 rounded-full bg-gradient-to-r from-gold to-amber-500 px-6 py-2.5 text-sm font-bold text-void shadow-lg hover:shadow-xl hover:brightness-110 transition-all"> View Plans <ArrowRight className="h-4 w-4"/> </Link> </div> );
} /* ── Main Export ─────────────────────────────────────────────────────────────── */ /** * FeatureGate — Wraps a feature with plan-aware access control. * * When `enabled` is false, renders either: * - A compact lock badge (when `compact` is true) * - A full upgrade prompt overlay (default) * * @example * <FeatureGate enabled={plan === 'enterprise'} featureName="AI Video Interviews"requiredPlan="enterprise"> * <VideoInterviewPanel /> * </FeatureGate> */ export function FeatureGate({ children, enabled, featureName, requiredPlan, compact = false, upgradeHref,
}: FeatureGateProps) { if (enabled) return <>{children}</>; if (compact) { return <CompactGate featureName={featureName} requiredPlan={requiredPlan} />; } return <FullGate featureName={featureName} requiredPlan={requiredPlan} upgradeHref={upgradeHref} />;
}
