'use client'; import React, { useState, useCallback, useRef } from 'react';
import clsx from 'clsx'; type GlassButtonVariant = 'primary' | 'secondary' | 'ghost' | 'danger' | 'gold' | 'aqua' | 'jade';
type GlassButtonSize = 'xs' | 'sm' | 'md' | 'lg' | 'xl'; interface GlassButtonProps extends React.ButtonHTMLAttributes<HTMLButtonElement> { /** * Visual variant determining the glow color and background * @default 'secondary' */ variant?: GlassButtonVariant; /** * Size of the button * @default 'md' */ size?: GlassButtonSize; /** * Show loading spinner */ loading?: boolean; /** * Icon to render on the left side */ leftIcon?: React.ReactNode; /** * Icon to render on the right side */ rightIcon?: React.ReactNode; /** * Full width button */ fullWidth?: boolean;
} const VARIANT_MAP: Record<GlassButtonVariant, string> = { 
  primary: 'bg-gradient-to-r from-[#00E5AB] to-[#1E68E5] text-[#051124] font-black ' + 
           'shadow-[0_4px_20px_rgba(0,229,171,0.3),inset_0_-2px_10px_rgba(0,0,0,0.2),inset_0_2px_10px_rgba(255,255,255,0.4)] hover:shadow-[0_8px_30px_rgba(30,104,229,0.5),inset_0_-2px_10px_rgba(0,0,0,0.2),inset_0_2px_10px_rgba(255,255,255,0.6)] ' + 
           'hover:from-[#00FFBE] hover:to-[#2B7AFF] border border-white/20', 
  secondary: 'bg-[#051124]/80 text-white border border-[#1E68E5]/30 backdrop-blur-xl ' + 
             'hover:bg-[#0A1E3A] hover:border-[#00E5AB]/60 hover:text-white ' + 
             'shadow-[0_4px_12px_rgba(0,0,0,0.5),inset_0_1px_1px_rgba(255,255,255,0.1)] hover:shadow-[0_8px_20px_rgba(0,229,171,0.2),inset_0_1px_1px_rgba(255,255,255,0.2)]', 
  ghost: 'bg-transparent text-slate-300 border-transparent ' + 
         'hover:bg-white/5 hover:text-white hover:border-white/10', 
  danger: 'bg-gradient-to-r from-red-600/80 to-rose-600/80 text-white border border-red-500/30 ' + 
          'hover:from-red-500 hover:to-rose-500 shadow-[0_4px_14px_rgba(220,38,38,0.2)] ' + 
          'hover:shadow-[0_8px_22px_rgba(225,29,72,0.4)]', 
  gold: 'bg-gradient-to-r from-[#9A7D00] to-[#CFAE00] text-[#051124] font-bold border border-[#FFF4CC]/40 ' + 
        'hover:from-[#CFAE00] hover:to-[#FFD700] hover:text-[#051124] ' + 
        'shadow-[0_4px_20px_rgba(207,174,0,0.3),inset_0_-2px_5px_rgba(0,0,0,0.2),inset_0_2px_10px_rgba(255,255,255,0.5)] hover:shadow-[0_8px_30px_rgba(255,215,0,0.5)]', 
  aqua: 'bg-[#00E5AB]/10 text-[#00E5AB] border border-[#00E5AB]/30 backdrop-blur-md ' + 
        'hover:bg-[#00E5AB]/20 hover:border-[#00E5AB]/60 hover:text-[#00FFBE] ' + 
        'shadow-[0_0_15px_rgba(0,229,171,0.1)] hover:shadow-[0_0_25px_rgba(0,229,171,0.3)]', 
  jade: 'bg-[rgba(42,157,143,0.10)] text-[#2a9d8f] border-[rgba(42,157,143,0.25)] ' + 
        'hover:bg-[rgba(42,157,143,0.18)] hover:border-[rgba(42,157,143,0.40)] hover:text-[#4abdb0] ' + 
        'hover:shadow-[0_0_20px_rgba(42,157,143,0.20)]',
}; const SIZE_MAP: Record<GlassButtonSize, string> = { xs: 'h-7 px-3 text-[10px] tracking-widest font-black uppercase rounded-xl gap-1.5', sm: 'h-9 px-4 text-xs font-bold rounded-xl gap-2', md: 'h-11 px-5 text-sm font-semibold rounded-2xl gap-2', lg: 'h-13 px-7 text-base font-bold rounded-2xl gap-2.5', xl: 'h-16 px-9 text-lg font-black rounded-3xl gap-3',
}; function Spinner({ size }: { size: GlassButtonSize }) { const sizeClass = size === 'xs' || size === 'sm' ? 'h-3 w-3' : size === 'lg' || size === 'xl' ? 'h-5 w-5' : 'h-4 w-4'; return ( <svg className={clsx('animate-spin shrink-0', sizeClass)} xmlns="http://www.w3.org/2000/svg"fill="none"viewBox="0 0 24 24"aria-hidden="true"> <circle className="opacity-25"cx="12"cy="12"r="10"stroke="currentColor"strokeWidth="4"/> <path className="opacity-75"fill="currentColor"d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"/> </svg> );
} /** * GlassButton — Premium CyberGlass 2.0 Interactive Button * * Features: * - 7 variants with unique glass/glow aesthetics * - 5 size options * - Loading state with spinner * - Left/right icon slots * - Cinematic hover: scale lift + glow intensification * - Active press: scale-down haptic feel * - Magnetic hover effect (subtle translate toward cursor) * - Respects prefers-reduced-motion * - Full keyboard accessibility */
export function GlassButton({ children, variant = 'secondary', size = 'md', loading = false, leftIcon, rightIcon, fullWidth = false, disabled, className, ...rest
}: GlassButtonProps) { const btnRef = useRef<HTMLButtonElement>(null); const [magnetOffset, setMagnetOffset] = useState({ x: 0, y: 0 }); const handleMouseMove = useCallback((e: React.MouseEvent<HTMLButtonElement>) => { if (!btnRef.current) return; if (window.matchMedia('(prefers-reduced-motion: reduce)').matches) return; const rect = btnRef.current.getBoundingClientRect(); const cx = rect.left + rect.width / 2; const cy = rect.top + rect.height / 2; const dx = (e.clientX - cx) * 0.12; /* subtle magnetic pull */ const dy = (e.clientY - cy) * 0.12; setMagnetOffset({ x: dx, y: dy }); }, []); const handleMouseLeave = useCallback(() => { setMagnetOffset({ x: 0, y: 0 }); }, []); const isDisabled = disabled || loading; return ( <button ref={btnRef} disabled={isDisabled} onMouseMove={handleMouseMove} onMouseLeave={handleMouseLeave} style={{ transform: magnetOffset.x !== 0 || magnetOffset.y !== 0 ? `translate(${magnetOffset.x}px, ${magnetOffset.y}px)` : undefined, transition: magnetOffset.x === 0 && magnetOffset.y === 0 ? 'transform 300ms cubic-bezier(0.16, 1, 0.3, 1), box-shadow 200ms, background 150ms, opacity 150ms' : 'transform 80ms linear, box-shadow 200ms, background 150ms', }} className={clsx( /* Base */ 'relative inline-flex items-center justify-center overflow-hidden', 'border transition-colors', 'select-none cursor-pointer', /* Variant */ VARIANT_MAP[variant], /* Size */ SIZE_MAP[size], /* Full width */ fullWidth ? 'w-full' : undefined, /* Scale animations */ !isDisabled && 'hover:-translate-y-px active:scale-[0.97]', /* Disabled */ isDisabled && 'opacity-50 cursor-not-allowed pointer-events-none', className, )} {...rest} > {/* Shimmer highlight on top rim */} <div className="pointer-events-none absolute inset-x-0 top-0 h-px bg-gradient-to-r from-transparent via-white/25 to-transparent"aria-hidden="true"/> {loading ? <Spinner size={size} /> : leftIcon} {children && <span>{children}</span>} {!loading && rightIcon} </button> );
}
