import { Column, Entity, Index, Unique } from 'typeorm';
import { TenantScopedEntity } from './tenant-scoped.entity';

/**
 * PROCESSED EVENT ENTITY — IDEMPOTENCY STORE
 *
 * Records every domain event that has been successfully processed by a
 * specific projection handler. The combination of (eventId, handlerName)
 * is the deduplication key.
 *
 * Purpose:
 *   When the same event arrives twice — due to retry, redelivery,
 *   dead-letter reprocessing, or explicit replay — the handler checks this
 *   table before executing. If a record exists, the handler skips.
 *
 * Scope:
 *   - tenantId is included because event IDs are generated globally and
 *     a replay of tenant-A events should not block tenant-B idempotency keys.
 *   - handlerName scopes the record per downstream system:
 *     AuditHandler and SearchHandler both handle the same event,
 *     but each needs its own idempotency record.
 *
 * Immutability:
 *   Rows are NEVER updated. If a handler fails after marking processed,
 *   the recovery path is manual investigation — not deletion of the record.
 *   The idempotency record is the forensic proof that the handler fired.
 *
 * Cleanup:
 *   expiresAt enables TTL-based cleanup by a background job.
 *   Default TTL is 30 days (configurable via ReplayProtectionStore).
 *   Null expiresAt = never expire (used for critical events like audit writes).
 *
 * Replay safety:
 *   This entity enables handlers to evolve independently:
 *   - A handler can be safely re-deployed without replaying already-processed events.
 *   - A replay tooling pass can clear specific handler records to force reprocessing.
 *   - A broken handler can be fixed and its records cleared for targeted replay.
 */
@Entity({ name: 'governance_processed_events' })
@Unique('UQ_processed_event_handler', ['eventId', 'handlerName'])
@Index(['tenantId', 'handlerName', 'processedAt'])
@Index(['eventId'])
@Index(['expiresAt'])
export class ProcessedEventEntity extends TenantScopedEntity {
  /**
   * UUID from DomainEventEnvelope.id — the globally unique event identity.
   * Generated by DomainEventBus at emission time.
   */
  @Index()
  @Column({ name: 'event_id', type: 'uuid' })
  eventId!: string;

  /**
   * Name of the handler that processed this event.
   * Matches ProjectionHandler.name — e.g. 'AuditProjectionHandler'.
   * Scopes idempotency per downstream system.
   */
  @Column({ name: 'handler_name', type: 'varchar', length: 100 })
  handlerName!: string;

  /**
   * Canonical event name (from domain-events.ts) at processing time.
   * Stored for forensic querying: "show all audit events processed this week".
   */
  @Column({ name: 'event_name', type: 'varchar', length: 100 })
  eventName!: string;

  /**
   * The aggregateId from the envelope — stored for replay targeting.
   * "Clear all processed records for PayrollBatch X so it can be replayed."
   */
  @Column({ name: 'aggregate_id', type: 'uuid', nullable: true })
  aggregateId!: string | null;

  /**
   * The aggregateType from the envelope — stored for replay type filtering.
   * "Clear all audit processed records for PayrollBatch type."
   */
  @Column({ name: 'aggregate_type', type: 'varchar', length: 100, nullable: true })
  aggregateType!: string | null;

  /**
   * Timestamp when the handler completed successfully.
   * Combined with processedAt and createdAt, enables exact handler execution timing.
   */
  @Column({ name: 'processed_at', type: 'timestamp with time zone' })
  processedAt!: Date;

  /**
   * TTL expiry timestamp for cleanup job.
   * Null = never expire (e.g. audit writes are permanent idempotency records).
   * Non-null = background cleanup job removes after this timestamp.
   */
  @Index()
  @Column({ name: 'expires_at', type: 'timestamp with time zone', nullable: true })
  expiresAt!: Date | null;

  /**
   * Optional execution duration in milliseconds — for handler performance monitoring.
   * Used by GovernanceSpanFactory to emit latency metrics.
   */
  @Column({ name: 'duration_ms', type: 'integer', nullable: true })
  durationMs!: number | null;
}
