apiVersion: v2
name: akul-dravin-hrms
description: Enterprise HRMS/ERP/CRM platform — Akul Dravin
type: application
version: 1.0.0
appVersion: "1.0.0"

keywords:
  - hrms
  - erp
  - crm
  - saas
  - multi-tenant
  - enterprise

maintainers:
  - name: Akul Dravin Engineering
    email: engineering@akuldravin.com

dependencies:
  - name: postgresql
    version: "13.x.x"
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled

  - name: redis
    version: "18.x.x"
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
